DROP TABLE INSTRUCTOR;

CREATE TABLE INSTRUCTOR(
    INS_ID INTEGER NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    FIRSTNAME VARCHAR(30) NOT NULL,
    CITY VARCHAR(30) ,
    COUNTRY CHAR(2),
    PRIMARY KEY(INS_ID)
  );

INSERT
  INTO INSTRUCTOR
(INS_ID, LASTNAME, FIRSTNAME, CITY, COUNTRY)
  VALUES
(1, 'Ahuja' , 'Rav' , 'Toronto', 'CA');

INSERT
  INTO INSTRUCTOR
(INS_ID, LASTNAME, FIRSTNAME, CITY, COUNTRY)
  VALUES
(2, 'Chong' , 'Raul' , 'Toronto', 'CA') ,
(3,'Vasudevan','Hima', 'Chicago', 'US');

SELECT * FROM INSTRUCTOR;

SELECT FIRSTNAME, LASTNAME, COUNTRY
  FROM INSTRUCTOR
  WHERE COUNTRY='CA';
  
 UPDATE INSTRUCTOR SET city='Markham' WHERE INS_ID=1;
 
 DELETE FROM INSTRUCTOR WHERE INS_ID=2;